import pyttsx3

try:
        text_speech = pyttsx3.init()
        nama_presiden ={'Afghanistan':' Hibatullah Akhundzada',
'Albania':' Bajram Begaj',
'Algeria':' Abdelmadjid Tebboune',
'Andorra':' Xavier Espot Zamora',
'Angola':' João Lourenço',
'Antigua and Barbuda':'Gaston Browne',
'Argentina':'Alberto Fernández',
'Armenia':'Vahagn Khachaturyan',
'Australia':'Anthony Albanese',
'Austria':' Alexander Van der Bellen',
'Azerbaijan':' Ilham Aliyev',
'The Bahamas':'Philip Davis',
'Bahrain':' Sheikh Hamad bin Isa Al Khalifa',
'Bangladesh':' Mohammed Shahabuddin',
'Barbados':' Dame Sandra Mason',
'Belarus':' Alexander Lukashenko[γ]',
'Belgium':' Philippe',
'Belize':'Johnny Briceño',
'Benin':' Patrice Talon',
'Bhutan':' Jigme Khesar Namgyel Wangchuck',
'Bolivia':' Luis Arce',
'Bosnia and Herzegovina':'Denis Bećirović',
'Botswana':' Mokgweetsi Masisi',
'Brazil':' Luiz Inácio Lula da Silva',
'Brunei':' Hassanal Bolkiah',
'Bulgaria':' Rumen Radev',
'Burkina Faso':' Ibrahim Traoré',
'Burundi':' Évariste Ndayishimiye[γ]',
'Cambodia':' Hun Sen[1]',
'Cameroon':' Paul Biya[γ]',
'Canada':' Justin Trudeau',
'Cape Verde':' José Maria Neves',
'Central African Republic':' Faustin Archange Touadéra[γ]',
'Chad':' Mahamat Déby',
'Chile':' Gabriel Boric',
'China':' Xi Jinping',
'Colombia':' Gustavo Petro',
'Comoros':' Azali Assoumani',
'Democratic Republic of the Congo':' Félix Tshisekedi',
'Republic of the Congo':' Denis Sassou Nguesso',
'Costa Rica':' Rodrigo Chaves Robles',
'Croatia':' Zoran Milanović',
'Cuba':' Miguel Díaz Canel',
'Cyprus':' Nikos Christodoulides',
'Czech Republic':' Petr Pavel',
'Denmark':' Margrethe II',
'Djibouti':' Ismaïl Omar Guelleh[γ]',
'Dominica':' Sylvanie Burton',
'Dominican Republic':' Luis Abinader',
'East Timor':' José Ramos Horta',
'Ecuador':' Guillermo Lasso',
'Egypt':' Abdel Fattah el Sisi',
'El Salvador':' Nayib Bukele',
'Equatorial Guinea':' Teodoro Obiang Nguema Mbasogo[γ]',
'Eritrea':' Isaias Afwerki',
'Estonia':' Alar Karis',
'Eswatini':' Mswati III',
'Ethiopia':' Sahle Work Zewde',
'Fiji':' Ratu Wiliame Katonivere',
'Finland':' Sauli Niinistö',
'France':' Emmanuel Macron[α]',
'Gabon':' Brice Clotaire Oligui Nguema[2]',
'Gambia, The':' Adama Barrow',
'Georgia':' Salome Zourabichvili',
'Germany':' Frank Walter Steinmeier',
'Ghana':' Nana Akufo Addo',
'Greece':' Katerina Sakellaropoulou',
'Grenada':' Dickon Mitchell',
'Guatemala':' Alejandro Giammattei',
'Guinea':' Mamady Doumbouya',
'Guinea-Bissau':' Umaro Sissoco Embaló',
'Guyana':' Irfaan Ali[γ]',
'Haiti':' Vacant[ζ]',
'Honduras':' Xiomara Castro',
'Hungary':' Katalin Novák',
'Iceland':' Guðni Th. Jóhannesson',
'India':' Droupadi Murmu',
'Indonesia':' Joko Widodo',
'Iran':' Ali Khamenei[η]',
'Iraq':' Abdul Latif Rashid',
'Ireland':' Michael D. Higgins',
'Israel':' Isaac Herzog',
'Italy':' Sergio Mattarella',
'Ivory Coast':' Alassane Ouattara[γ]',
'Jamaica':' Andrew Holness',
'Japan':' Naruhito[θ]',
'Jordan':' Abdullah II',
'Kazakhstan':' Kassym Jomart Tokayev[γ]',
'Kenya':' William Ruto',
'Kiribati':' Taneti Maamau',
'Kuwait':' Sheikh Nawaf Al Ahmad Al Jaber Al Sabah',
'Kyrgyzstan':' Sadyr Japarov[γ]',
'Laos':' Thongloun Sisoulith',
'Latvia':' Edgars Rinkēvičs',
'Lebanon':' Vacant',
'Lesotho':' Letsie III',
'Liberia':' George Weah',
'Libya':' Mohamed al Menfi',
'Liechtenstein':' Hans Adam II',
'Lithuania':' Gitanas Nausėda',
'Luxembourg':' Henri',
'Madagascar':' Richard Ravalomanana',
'Malawi':' Lazarus Chakwera',
'Malaysia':'Pertuan Agong   Abdullah Sultan Ahmad Shah',
'Maldives':' Ibrahim Mohamed Solih',
'Mali':' Assimi Goïta[γ]',
'Malta':' George Vella',
'Marshall Islands':' David Kabua',
'Mauritania':' Mohamed Ould Ghazouani',
'Mauritius':' Prithvirajsing Roopun',
'Mexico':' Andrés Manuel López Obrador',
'Federated States of Micronesia':' Wesley Simina',
'Moldova':' Maia Sandu',
'Monaco':' Albert II',
'Mongolia':' Ukhnaagiin Khürelsükh',
'Montenegro':' Jakov Milatović',
'Morocco':' Mohammed VI',
'Mozambique':' Filipe Nyusi[γ]',
'Myanmar':' Min Aung Hlaing',
'Namibia':' Hage Geingob[γ]',
'Nauru':' David Adeang',
'Nepal':' Ram Chandra Poudel',
'Netherlands':' Willem Alexander',
'New Zealand':' Chris Hipkins',
'Nicaragua':' Daniel Ortega',
'Nigeria':' Bola Tinubu',
'North Korea':' Kim Jong Un',
'North Macedonia':' Stevo Pendarovski',
'Norway':' Harald V',
'Oman':' Haitham bin Tariq',
'Pakistan':' Arif Alvi',
'Palau':' Surangel Whipps Jr.',
'Palestine':' Mahmoud Abbas',
'Panama':' Laurentino Cortizo',
'Papua New Guinea':' James Marape',
'Paraguay':' Santiago Peña',
'Peru':' Dina Boluarte[γ]',
'Philippines':' Bongbong Marcos',
'Poland':' Andrzej Duda',
'Portugal':' Marcelo Rebelo de Sousa',
'Qatar':' Sheikh Tamim bin Hamad Al Thani',
'Romania':' Klaus Iohannis',
'Russia':' Vladimir Putin',
'Rwanda':' Paul Kagame[γ]',
'Saint Kitts and Nevis':' Terrance Drew',
'Saint Lucia':' Philip J. Pierre',
'Saint Vincent and the Grenadines':' Ralph Gonsalves',
'Samoa':' Afioga Tuimalealiʻifano Vaʻaletoʻa Sualauvi II',
'San Marino':' Filippo Tamagnini',
'São Tomé and Príncipe':' Carlos Vila Nova',
'Saudi Arabia':' Salman',
'Senegal':' Macky Sall[γ]',
'Serbia':' Aleksandar Vučić',
'Seychelles':' Wavel Ramkalawan',
'Sierra Leone':' Julius Maada Bio[γ]',
'Singapore':' Tharman Shanmugaratnam',
'Slovakia':' Zuzana Čaputová',
'Slovenia':' Nataša Pirc Musar',
'Solomon Islands':' Manasseh Sogavare',
'Somalia':' Hassan Sheikh Mohamud',
'South Africa':' Cyril Ramaphosa',
'South Korea':' Yoon Suk yeol[γ]',
'South Sudan':' Salva Kiir Mayardit',
'Spain':' Felipe VI',
'Sri Lanka':' Ranil Wickremesinghe[γ]',
'Sudan':'Burhan (Chairman)',
'Suriname':' Chan Santokhi',
'Sweden':' Carl XVI Gustaf',
'Switzerland':'',
'Syria':' Bashar al Assad[γ]',
'Tajikistan':' Emomali Rahmon[γ]',
'Tanzania':' Samia Suluhu Hassan[γ]',
'Thailand':' Maha Vajiralongkorn',
'Togo':' Faure Gnassingbé[γ]',
'Tonga':' Tupou VI',
'Trinidad and Tobago':' Christine Kangaloo',
'Tunisia':' Kaïs Saïed[γ]',
'Turkey':' Recep Tayyip Erdoğan',
'Turkmenistan':' Serdar Berdimuhamedow',
'Tuvalu':' Kausea Natano',
'Uganda':' Yoweri Museveni[γ]',
'Ukraine':' Volodymyr Zelenskyy',
'United Arab Emirates':' Sheikh Mohamed bin Zayed Al Nahyan',
'United Kingdom':' Charles III',
'United States':' Joe Biden',
'Uruguay':' Luis Lacalle Pou',
'Uzbekistan':' Shavkat Mirziyoyev[γ]',
'Vanuatu':' Nikenike Vurobaravu',
'Vatican City':' Pope Francis',
'Venezuela':' Nicolás Maduro',
'Vietnam':' Võ Văn Thưởng',
'Yemen':' Rashad al Alimi',
'Zambia':' Hakainde Hichilema',
'Zimbabwe':' Emmerson Mnangagwa'}
        nama = input('Input the Country Name : ')
#if  nama == nama_presiden
        print(nama_presiden[nama.title()])
        text_speech.say(nama_presiden[nama.title()])
        text_speech.runAndWait()
except:
        salah = "there is no country named as "
        print (salah + nama)
        text_speech.say(salah + nama)
        text_speech.runAndWait()